# Python Crash Course

## Table of Contents

- **Introduction**
    - [What is Python?](#What-is-Python)
    - [Why do we use Python?](#Why-use-Python)

- **Python Review**
    - [Variables](#Variables)
    - [Input/Output](#Input/Output)
    - Operators 
        - [Arithmatic Operators](#1.-Arithmatic-Operators)
        - [Relational Operators](#2.-Relational-Operators)
        - [Logical Operators](#3.-Logical-Operators)
    - DataTypes
    - Containers
        - [Lists](#Lists)
        - [Tuples](#Tuples)
        - [Sets](#Sets)
        - [Dictionaries](#Dictionaries)
        - [Identity Operator and Aliasing](#Identity-Operator-and-Aliasing)
        - [Special Operator '+' and '+=' on Lists and Tuples](#Special-Operator-'+'-and-'+='-on-Lists-and-Tuples)
        
    - Flow Control Statements
        - [If Statements](#If-Statement)
        - [For Loop](#For-Loop)
        - [While Loop](#While-Loops)
        - [List Comprehension](#List-Comprehension)
       
    - Functions
        - [Functions](#Functions)
        - [Lambda Functions](#Lambda-Functions)
    - [Exception Handling](#Exception-Handling)
- **Advanced Python**
    - Object Oriented Programming
        - [Classes](#Classes:)
        - [Inheritance and Polymorphic Behavior](#Inheritance-and-Polymorphic-Behavior)
    - [File IO](#File-IO)
- **Numpy**
    - [How to use NumPy](#How-to-use-numpy)
    - [Arrays in NumPy](#Arrays-in-NumPy)
    - [Matrix Operations](#Matrix-Operations-in-NumPy)
    - [Broadcasting](#Broadcasting-in-NumPy)
    - [Masked Indexing](#Masked-Indexing)
    - [Aggregation](#Aggregation)
- **Pandas**
    - [Reading Data Files](#Reading-Data-Files-in-Pandas)
    - [Indexing in Pandas](#Indexing-in-Pandas)
- [NumPy and Pandas Requirement](#Requirement-on-NumPy)

- **MatPlot Lib**
    - [Line Plots](#Line-Plots)
    - [Scatter Plots](#Scatter-Plots)
    - [Histogram Plots](#Histogram-Plots)
    - [Pie Charts](#Pie-Charts)
    - [Multiple Plots on the Same Figure](#Multiple-Plots-on-the-Same-Figure)
    - [Plotting Requirement](#Requirement-on-MatPlotLib)


### What is Python?

Python is the most popular high-level programming language to our time. It is popular for its wide range of applications in web development and machine learning, with a special advantage in scripting and demoing. As you will see later in the lab, it takes a few lines to implement complex programs. 

Unlike most programming languages that you may have worked with, Python is an **interpreted language** and not a compiled one. This means means that a python file is executed line by line from top to down. If a line contains error(s), execution will stop at this line. 

Despite this fact, Python is flexible enough to write **object oriented programs** as well as **procedural (also knwon as functional) programs**. We will discuss when to use each as a best practice later in this lab. 

### Why do we use Python?
Python is probably the largest open-source programming language in the world. This means there is nothing you will need that is not  available in Python on the internet. 

Development time in python is faster than any other language: usually what people do in large companies is simply quick demos (prototyping) using python until they are satisfied with the results, then implement in other languages for better performance or system requirements. 

Python skills is a necessity for all students in computer science and engineering. Regardless the field you will work in, you will probably use Python.

---------------------

# Python Review

## Variables 
Variables in python do not have specific type until they are assigned a value. In order to know the type of a variable, we use the special funtion "type()".

**Note: To run a cell, select it with Ctrl+Enter**.

In [1]:
integer_variable = 1
print(type(integer_variable)) ## integer class

floating_variable = 1.0
print(type(floating_variable)) ## floating class

boolean_variable = True
print(type(boolean_variable)) ## boolean class

string_variable = "I am a String"
print(type(string_variable)) ## string class

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'str'>


In order to check if a variable is of specific data type, we use the function isinstance(variable, data type)

In [4]:
## for example
integer_var = 5
print(isinstance(integer_var,int)) ## returns True
print(isinstance(integer_var, bool)) ## returns False
print(not isinstance(integer_var, bool)) ## returns True, due to the use of not

True
True


Like the NULL value in other programming languages, Python uses the 'None' keyword to mark unknown values for variables

In [5]:
unknown_variable = None
print(type(unknown_variable))

<class 'NoneType'>


In [6]:
## we can check on its type as well
print(isinstance(unknown_variable, int)) ## returns False

## But to check if a variable is none, we use the identity operator 'is', we will discuss the identity
## operator later in this lab
print(unknown_variable is None) ## returns True

False
True


---------------------

## Input/Output

In order to output any data to screen, you only need to use the function "print()".
The function allows you to control the output format in a very flexible way. 

In [7]:
## You can pass the output string directly
print("Python is easy to learn!") 

## You can pass multiple objects to output
print("This is a string", "and this is another one!")

Python is easy to learn!
This is a string and this is another one!


In [8]:
## You can ouput objects other than strings
print("Hi! I am", 23, "Years old")

## Even print lists (we will discuss lists later, don't worry ;) )
primes = [2, 3, 5, 7]
print("Prime numbers less than 10 are: ", primes)

Hi! I am 23 Years old
Prime numbers less than 10 are:  [2, 3, 5, 7]


In [12]:
## THIS IS NEW FOR ME. I DID NOT KNOW THIS

## a special parameter to the 'print' function is called "sep" which is used to separate the objects to be printed
## see how we use arrows ->
print("I can count from 1", "10", sep='->')
## and this one uses hyphens
print("This lab is legen", "wait for it", "dary", sep="-")

## remember: the default separator is blank space ' '

## another special parameter is called "end" which is used to specify what to print at the end of the output
## by default it is a new line character
print("This line will end with smile", end=" :).")

I can count from 1->10
This lab is legen-wait for it-dary
This line will end with smile :).

Taking inputs in python is as easy as presenting output: All you need to use is the function "input()"

In [17]:
## the funtion input() takes as a parameter a string: this is the message that prompts the user to give an input
age = input("Hi! How old are you?")
print("You are", age, "years old!", sep=" => ")

You are => 21 => years old!


**IMPORTANT NOTE** the input function always returns values as **STRINGS**, you will see later how to cast these to other types 

---------------------

## Operators
Like all programming languages, Operators in Python are categoriezed into Arithmatic, Relational and Logical operators. We will discuss them all in details here.

### 1. Arithmatic Operators
Arithmetic operators are used to perform mathematical operations like addition, subtraction, multiplication and division

In [18]:
## addition: +
print('1 + 2 =', 1 + 2) ## add two numbers

## subtraction: -
print('3 - 2 =', 3 - 2) ## subtract two numbers

## multiplication:
print('3 * 2 =', 3 * 2) ## multiply two numbers

## self addition
x = 2
x += 2 ## add to x and assigns value to x again
print('x = 2 + 2 =', x) 

## self subtraction
x = 2
x -= 2 ## subtracts from x and assigns value to x again
print('x = 2 - 2 =', x) 

## self multiply
x = 2
x *= 2 ## multiplies from x and assigns value to x again
print('x = 2 * 2 =', x) 

1 + 2 = 3
3 - 2 = 1
3 * 2 = 6
x = 2 + 2 = 4
x = 2 - 2 = 0
x = 2 * 2 = 4


In [20]:
## modulus operator: x%y returns the remainder of dividing the x by y
print(5%2) ## dividing 5 by 2 gives two twos and the remainder is 1

## self modulus
x = 5
x %= 2 ## calculates modulus of x by 2 and assigns value to x again
print('x = 5 % 2 =', x) 

1
x = 5 % 2 = 1


In [19]:
## power operator: x**y returns the value of raising x to the power of y
print(3**2) ## 3 to the power of 2 is 9

## self power
x = 5
x **= 2 ## calculates power of x to 2 and assigns value to x again
print('x = 5 ^ 2 =', x) 

9
x = 5 ^ 2 = 25


**NOTICE** only if both values are integers, the output is integer. If one of the operands is floating point, the output is floating point


In [21]:
print(2*2.0) ## this returns float value
print(2*2) ## this returns integer value

4.0
4


**Division** in python is tricky! 

In [22]:
## The operator x/y returns floating value of dividing x by y
print(5/2) ## returns 2.5

## self floating point division
x = 5
x /= 2 ## calculates quotient of dividing x by 2 and assigns value to x again
print('x = 5 / 2 =', x) 

2.5
x = 5 / 2 = 2.5


In [23]:
## The operator x//y returns the integer floor value of dividing x by y
print(5//2) ## returns 2

## self integer division
x = 5
x //= 2 ## calculates quotient of dividing x by 2 and assigns value to x again
print('x = 5 // 2 =', x) 

2
x = 5 // 2 = 2


### 2. Relational Operators
Relational operators compares the values of the operands

In [24]:
print(5 > 7) ## Checks if 5 greater than 7
print(5 >= 7) ## Checks if 5 greater than or equal to 7

print(5 < 7) ## Checks if 5 less than 7
print(5 <= 7) ## Checks if 5 less than or equal 7

print(5 == 7) ## Checks if 5 equal to 7
print(5 != 7) ## Checks if 5 not equal to 7

False
False
True
True
False
True


### 3. Logical Operators

In [26]:
condition_1 = True
condition_2 = False
print(condition_1 and condition_2) ## Logic AND of condition 1 and condition 2
print(condition_1 or condition_2) ## Logic OR of condition 1 and condition 2
print(not condition_1) ## Logic NOT of condition 1

False
True
False


---------------------

## Data Types
As you saw, Python contains all the primitive data types as any language:
- Integer  
- Boolean
- Float   
- String

---------------------

## Containers
Python also contains Containers that associate multiple values like:
- Lists
- Tuples
- Sets
- Dictionaries

### Lists
Lists in python are like dynamic sized arrays. Lists are denoted by the square brackets [ ] where entries in list are separated by commas.

In [27]:
## List declaration is simple
list_of_numbers = [1, 2, 3] 
print(list_of_numbers)

[1, 2, 3]


Unlike most programming languages, Lists in python can contain variables of different types

In [28]:
## for example
different_types_list = ["I am a String", 23, True] ## list of string, integer and boolean!
print(different_types_list)

['I am a String', 23, True]


In [29]:
## to get the length of list, we use the len() function
three_entries_list = [1, 2, 3]
print(len(three_entries_list)) ## length of the list is 3

3


#### Indexing lists in Python
Indexing lists is very simple in python. Indexes start from zero to length of the list -1. However, there are some special indexing tricks you need to know about.

In [30]:
sample_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## to get the 1st entry in the list
print(sample_list[0])

## to get the 3rd entry in the list
print(sample_list[2])

1
3


**IMPORTANT** Special indexing in python

In [31]:
sample_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## to get the last entry
print(sample_list[-1])

## to get the second-to-last entry
print(sample_list[-2])

10
9


Python allows to index sub-lists from the longer list using the colon 'start-index : end-index' operator. 

**NOTE** the end-index is NOT included in the sublist (the start-index is inclusive while the end-index is exclusive).

In [32]:
sample_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## access the 3rd, 4th and the 5th elements, we start from index 2 to index 5 (not index 5)
sublist = sample_list[2:5]
print(sublist)

[3, 4, 5]


In [33]:
sample_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## to access elements from the start of the list to a specific index, we do not use start index
first_three_elements = sample_list[:3]
print(first_three_elements)

[1, 2, 3]


In [34]:
sample_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## likewise, to access from the 7th element to the end of the list 
## Remember: we do NOT know the length of the list
from_seventh_element = sample_list[6:] ## similar to sample_list[6:len(sample_list)]
print(from_seventh_element)

[7, 8, 9, 10]


In [37]:
#### TEST YOURSELF #### -> Succeeded :)
## write One line to get the last 3 elements from the list
## HINT: Combine sub-list indexing and the negative indices concepts we just revised
sample_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
last_three_elements = sample_list[-3:]
print(last_three_elements)

[8, 9, 10]


In [38]:
## I didn't know this.
## we can control the step by wich we increment the sublist indexes
## using format 'start-index:end-index:increment-value'

## for example, we can get elements at even indices up to the fifth element
even_indices_elements = sample_list[0:5:2]
print(even_indices_elements)

[1, 3, 5]


### Tuples

Tuples are exactly like lists in python, the **ONLY difference** is that tuples are **immutable** but lists are **mutable**

Immutable means: we cannot modify tuples once they are created: you cannot change elements, delete from them or add to the tuple.

Tuples are denoted by round brackets '()'.

In [40]:
tuple_example = (1,2)
# tuple_example[0] = 4 ## this will cause an error called: tuple object does not support item assignment

**NOTE** Make sure you understand that in the previous example, tuple_example is a VARIABLE, we can re-assign anything to it. However, when it is of type Tuple, we cannot assign to the **ELEMENTS** of the tuple.

Indexing tuples is exactly like the lists

In [41]:
## indexing sub-tuple from tuples
vegetables_tuple = ("Tomato", "Potato", "Cucumber", "Carrots", "Eggplants")

first_two_elements_tuple = vegetables_tuple[:2] ## creates a sub-tuple  of the first two elements
print(first_two_elements_tuple) 

('Tomato', 'Potato')


We can cast lists into tuples and vise versa

In [43]:
sample_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
tuple_from_list = tuple(sample_list)
print(type(tuple_from_list)) ## it is of class tuple

## and the other way round
vegetables_tuple = ("Tomato", "Potato", "Cucumber", "Carrots", "Eggplants")
list_from_tuple = list(vegetables_tuple)
print(type(list_from_tuple)) ## it is of class list

# after this casting we can access its elements and modify them 
list_from_tuple[0] = "Carrots"
print(list_from_tuple)

<class 'tuple'>
<class 'list'>
['Carrots', 'Potato', 'Cucumber', 'Carrots', 'Eggplants']


**IMPORTANT** If tuples and lists are necissarily the same, why do we need tuples? Because:

Since tuples are immutable (cannot be changed) they are saved in memory as one chunck of data. This makes it faster in access time and more memory efficient (certain compression techniques are used over tuples on byte level).

##### When to use Tuples over lists:
* When you have a fixed element list (for example: languages that your program support are English, French or Arabic) it is more efficient to save the list of accepted languages in a tuple.
* When you want to prevent the change of the elements of the list resulting from a certain function (for example, a function returns the acceptable values in your program, it is more safe to return them in tuple instead of list so that callers of this function do not mistakenly change these values).


### Sets
Sets are special type of lists where all elements are **Unique**, they are denoted by curly parentheses '{}'

In [44]:
### Notice the difference
non_unique_list = [1, 1, 2, 2, 3, 3]
print(non_unique_list)

unique_set = {1, 1, 2, 2, 3, 3}
print(unique_set)

[1, 1, 2, 2, 3, 3]
{1, 2, 3}


In [45]:
### you can cast the list into set
non_unique_list = [1, 1, 2, 2, 3, 3]
unique_elements_from_list = set(non_unique_list)
print(unique_elements_from_list)

{1, 2, 3}


### Dictionaries
Dictionaries are **Sets** of key-value pairs, where each key is associated by a pair. they are denoted also by the curly parentheses { key: value}, and elements are indexed by the keys, e.g. dictionary[key], or the get(key) function.

In [49]:
dictionary = {'a': 'Apple', 'b': 'Banana', 'c': 'Cat', 'd': 'Dog'}
print(dictionary['a'])
print(dictionary.get('c'))

Apple
Cat


**IMPORTANT** keys do not need to be of the same type, but they need to be **IMMUTABLE**. Also values can be of any data type.

In [53]:
different_keys_dictionary = { 
    'a': True, 
    23: "Is My Age", 
    ('Series', 'Netflix List') : ['Sherlock', 'Lucifer', 'Elite']
}

series_i_like = different_keys_dictionary[('Series', 'Netflix List')]
print(series_i_like)

['Sherlock', 'Lucifer', 'Elite']


---------------------

### Test Yourself:
What do you think will happen if we switched the list and the tuple from the last example:

i.e. if we make a dictionary: dic = {['Series', 'Netflix List']: ('Sherlock', 'Lucifer')}? 

**Justify your answer.**

*Hint: Remember keys must be immutable.*

**Note: Add a cell here answering these questions as mark-up text.**

* I believe that this will produce an error which is called unhashable type error
* the idea is that when we add a new key/value pair to a dictionary, the python interpreter generates a hash to the key
* this can occurs only on some data types in python which are hashable, but containers like lists and dictionaries are unhashable, so it will fail to generate a hash for them and this will cause throwing an exception.   

---------------------

### Identity Operator and Aliasing
Now that we know the containers objects in Python, a very important concept you need to know is the Identity operator 'is'.

Variables in python are all passed by **Reference**, that is: variables point to the location in memory where the value(s) is(are) stored.

So a program like this:

X = 5

Y = X

will create two reference (X and Y) that both point to the location of value 5 in memory, but will not copy the value 5 from X to Y.

**Notice** in the next example: we change the value of the second index of Y, but X still changes!

In [54]:
X = [5, 6, 7]
Y = X
Y[1] = True ## we change in Y

print('X is changed into: ', X)

X is changed into:  [5, True, 7]


The **equality** operator checks if the **Values** of both variables are the same! but the **Identity** operator checks if they both point to the **same memory location**.

In [57]:
X = [5, 6, 7]
Y = X
Z = [5,6,7]
W = [6,7,8]

print('Are Z and Y of the same values? ', Y == Z) ## YEP
print('Are W and Y of the same values? ', Y == W) ## NOPE
print('Are X and Y of the same memory location? ', Y is X) ## YEP
print('Are X and Y of the same memory location? ', X is Z) ## NOPE

Are Z and Y of the same values?  True
Are W and Y of the same values?  False
Are X and Y of the same memory location?  True
Are X and Y of the same memory location?  False


In [58]:
## But
X = [5, 6, 7]
Y = [5, 6, 7]

print('Are X and Y of the same values? ', Y == X) ## YEP
print('Are X and Y of the same memory location? ', Y is X) ## NOPE

Are X and Y of the same values?  True
Are X and Y of the same memory location?  False


**Pay Attention** because this common pitfall in python can cause serious errors in your program. 

So how can i copy the values of a variable into another? 

Use the copy library from python:

In [59]:
import copy ## this means we import the code from library called 'copy' into our workspace
X = [1, 2, 3]
Y = copy.deepcopy(X)

print('Are X and Y of the same values? ', Y == X) ## YEP
print('Are X and Y of the same memory location? ', Y is X) ## NOPE

# OR SIMPLY YOU Can use the copy method of the list
X = [1, 2, 3]
Y = X.copy()
print(Y is X)


Are X and Y of the same values?  True
Are X and Y of the same memory location?  False
False


### Special Operator '+' and '+=' on Lists and Tuples
It concatenates the containers values.

In [60]:
### concatenate two lists:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

concatenated_list = list1 + list2
print(concatenated_list)

## we self-append list 2 tp list 1
list1 += list2
print(list1)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


In [61]:
### concatenate two tuples:
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)

concatenated_tuples = tuple1 + tuple2
print(concatenated_tuples)

## we self-append tuple 2 to tuple 1
tuple1 += tuple2
print(tuple1)

(1, 2, 3, 4, 5, 6)
(1, 2, 3, 4, 5, 6)


---------------------

## Flow Control Statemets

Flow control statements are the statements that control flow of the code execution. In python, there are 3 types of these statements: If-else statemets, For-Loops and While Loops.

Notice: in python, there is no curly parentheses {} to define block scope of the statements, only indentations (tabs) that define these. Be aware of the indentations you make!

### If-Statement

the if statement block is executed when the condition specified evaluates to True. There are three types of if-statements:
* single if
* if-else statement
* multiple if statements

#### Single if:

In [62]:
age = 23
if age > 18: ## NOTICE: the condition ends with a colon, and does not need round brackets around it ()
    print('WOW, You are a grown up!') ### this block will be executed only if the age is above 18

WOW, You are a grown up!


#### If-Else statement

In [64]:
age = 16
if age > 18: 
    print('WOW, You are a grown up!') ### this block will be executed only if the age is above 18
else:
    print('Oh! You are young to be with us!') ### this block will be executed only if the age is not above 18

Oh! You are young to be with us!


#### Multiple If statement

In [63]:
age = 5
if age > 18:
    print('WOW, You are a grown up!') ### this block will be executed only if the age is above 18
elif age > 16:
    print('Oh! You are young to be with us!') ### this block will be executed only if the age is less than 18 and above 16
else:
    print('Ooopss! You are too young to be here!') ### this block will be executed only if all the above conditions dont work

Ooopss! You are too young to be here!


In [65]:
### nested if statements:
age = 19
if age > 18:
    print('Ok! you are old')
    
    if age < 20:
        print('LoL! but not old enough')
    else:
        print('You are good to go')
        
else:
    print('Thee shall not pass')

Ok! you are old
LoL! but not old enough


### For Loop
for loops in python can be used in multiple ways:

#### Loop for a range of values
we use the function range(start value, end value, increment step) **REMEMBER** the end value is not included in the range, and the start value default is zero

In [66]:
## loop for 5 times:
for index in range(0,5,1):
    print(index)

0
1
2
3
4


In [67]:
## loop for 5 times with step = 2
for even_indeces in range(0,10,2):
    print(even_indeces)

0
2
4
6
8


In [69]:
## loop from 4 to 10:
for index in range(4,11): ## notice: the last index is 10 not 11. 11 is excluded
    print(index)

4
5
6
7
8
9
10


In [70]:
## loop over elements in list: (similarly over tuples, sets and KEYS of dictionaries)
Cars = ['Mercedes', 'BMW', 'Fiat', 'Porsche', 'Ford']
for car in Cars: # this is called a for each loop
    print('I Love ', car)

I Love  Mercedes
I Love  BMW
I Love  Fiat
I Love  Porsche
I Love  Ford


### While Loops
Like other languages, while loops continue iterating until the condition is falsifiable.

In [71]:
maximum_allowance = 15
current_allowance = 10

while current_allowance < maximum_allowance:
    print('Your allowance is:', current_allowance, '$')
    print('OK, i will increase your allowance by 1$\n')
    current_allowance += 1

print("\nYour allowance is the maximum you can have:", current_allowance, "$")

Your allowance is: 10 $
OK, i will increase your allowance by 1$

Your allowance is: 11 $
OK, i will increase your allowance by 1$

Your allowance is: 12 $
OK, i will increase your allowance by 1$

Your allowance is: 13 $
OK, i will increase your allowance by 1$

Your allowance is: 14 $
OK, i will increase your allowance by 1$


Your allowance is the maximum you can have: 15 $


### List Comprehension
Python provides a cool compact way to generate lists using the syntax:

[ process `for` index `in` range ]

In [72]:
## make a list from 1 to 10 in one-liner
quick_list = [i for i in range(1, 11)] 
print(quick_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [73]:
## make a tuple of all alphabits in one-liner
alphabets = [chr(i) for i in range(ord('a'), ord('z')+1)]
print(alphabets)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [75]:
## nested lists are also possible, see the example below 
nested_loop_list = [chr(i) + str(j) for i in range(ord('a'),ord('d')+1) for j in range(1, 5)]
print(nested_loop_list)

['a1', 'a2', 'a3', 'a4', 'b1', 'b2', 'b3', 'b4', 'c1', 'c2', 'c3', 'c4', 'd1', 'd2', 'd3', 'd4']


it follows the syntax: 

[ process of inner loop `for` outer_loop_iterator `in` outer_loop_range  `for` inner_loop_index `in` inner_loop_range ] 

---------------------

## Functions
Python allows you to create functions for code modularity and reusability. a function is defined using the 'def function_name(parameters):' signature.

In [76]:
## this funtion returns the multiplication of 2 by the argument
def multiply_by_2(value):
    
    multiple = value * 2
    return multiple

response = multiply_by_2(2)
print("2 * 2 = ", response)

2 * 2 =  4


In [77]:
## functions need not return a value
def print_welcome_status():
    print("Hello! Nice to meet you!")
    
print_welcome_status()

Hello! Nice to meet you!


In [78]:
## functions can have default values for the arguments:
def default_value_function(value=0):
    print('The value is: ', value)
    
# Function call with default value::
default_value_function()
# Function call with non-default value::
default_value_function(4)

The value is:  0
The value is:  4


In [79]:
## if a function has too many arguments, and you don't remember the order of them, you can pass the values by naming the arguments regradless of order!
def too_much_parameters(param1, param2, param3, param4):
    
    print('parameter 1 is ', param1)
    print('parameter 2 is ', param2)    
    print('parameter 3 is ', param3)   
    print('parameter 4 is ', param4)   
    

too_much_parameters(param2=2, param4= 4, param1=1, param3=3) ## this
print("#########")
too_much_parameters(1,2,3,4) ## is exactly like this

parameter 1 is  1
parameter 2 is  2
parameter 3 is  3
parameter 4 is  4
#########
parameter 1 is  1
parameter 2 is  2
parameter 3 is  3
parameter 4 is  4


In [80]:
## if you want to define a funtion but leave it empty (for example override a function but no implementation yet)
## use the 'pass' keyword
def un_implemented_function():
    pass

un_implemented_function() ## executes nothing!

**IMPORTANT** Unlike other programming langauges, python can return multiple variables from a function

In [81]:
def get_sum_subtract_product_quotient(value1, value2):
    
    addition = value1 + value2
    subtraction = value1 - value2
    product = value1 * value2
    quotient = value1 / value2
    return addition, subtraction, product, quotient


add, sub, prod, quot = get_sum_subtract_product_quotient(5, 2)
print('5+2=', add)
print('5-2=', sub)
print('5*2=', prod)
print('5/2=', quot)

5+2= 7
5-2= 3
5*2= 10
5/2= 2.5


### Lambda Functions

Lambda functions are one-line anonymous functions. They are shortcuts for defining simple functions instead of the full `def` structure.

In [82]:
square = lambda x: x**2

print(square(5))

25


In [83]:
## gets distance of coordinates (x,y) from origin (0,0)
distance_from_origin = lambda x, y: (x**2 + y**2)**0.5 

print(distance_from_origin(3, 4))

5.0


---------------------

## Exception Handling
It is important to write non-crashing programs in any language. Of course, there is no flawless program (except in this lab, of course!), so we need to write specific code that handles exceptions that may occur.

Execption handling is simple: surround the vulnerable code with a try-except block. 

**Good Practice** provide expressive messages when handling errors, it will reduce time and give readable clean code.

In [84]:
def safe_divide(numerator, denominator):
    
    quotient = None ## quotient of dividing the numerator by the denominator
    try:
        quotient = numerator / denominator
    except ZeroDivisionError: ## if the denominator was zero, this exception will be thrown
        print('Denominator cannot be zero!')
        
    return quotient ## will return None if the exception is thrown, or the division result otherwise

In [85]:
safe_divide(10, 2) ## runs normally

5.0

In [86]:
safe_divide(10, 0) ## throws error

Denominator cannot be zero!


You can raise exceptions in your functions as well

In [87]:
## this function accepts only numeric values
def add_5(value):
    
    if not isinstance(value, int) and not isinstance(value, float):  ## check if calue is numeric
        raise TypeError('value must be nuemric, found: ', type(value))
        
    ## if it is numeric
    return value + 5

In [88]:
add_5(5) ## works just fine

10

In [89]:
add_5("5") ## this will raise exception

TypeError: ('value must be nuemric, found: ', <class 'str'>)

**GOOD PRACTICE** it is better to specify the type of exception in the 'except' block of course, but you can have a generic except block to catch any type of exceptions

In [90]:
def generic_excpetion_function():
    
    try:
        print('doing something nasty...')
        raise 'Some Exception'
    except: ## generic exception handling: catches any exception 
        print('caught generic exception')


In [91]:
generic_excpetion_function()

doing something nasty...
caught generic exception


---------------------






## Object Oriented Programming in Python
Pythons allows you to create user-defined classes with all OOP concepts: polymorphism, inheritance...etc.

In this section we will see how to use OOP in Python.

Although Python does not require binding functions and variables to specific classes to work, we usually need them for clean code and modularity.

### Classes:
To define a class, we use the 'def ClassName:' signature. 

Classes have two types of attributes:
* Class Attributes: Static variables that are shared by all objects of the class type, and can be accessed using the class name itself.

* Instance Attributes: Variables that differ in value from a class instance to another.

Classes have two types of methods:
* Class Methods should be annotated by the '@staticmethod' before method definition, it can be used by the Class name itself

* Instance Methods are associated by each instance, it **must** include the parameter 'self' at the beginning of the parameters list.

in order to make an instance attribute or instance method private, their names should start by two underscores '__methodName'

In [93]:
class PersonClass:
    
    ## in the class scope, we define the class variables and methods
    
    ## Class Attributes:
    
    ## class Attributes defined here are always PUBLIC and STATIC 
    nationality = 'American'
    
    ## class constructor
    def __init__(self, firstName, lastName):
        print('Person Constructor is Called')
        ## instance variable defiend here are public and differ from instance to another
        self.firstName = firstName
        self.lastName = lastName
        
        ## salary is a private instance variable
        self._salary = 5000
        
    
    ## class static method:
    @staticmethod
    def capitalized_nationality():
        return PersonClass.nationality.upper()
    
    ## instance methods:
    def get_full_name(self):
        return f'{self.firstName} {self.lastName}'
    
    ## private instance method:
    ## this method is not accessible from outside the class, we use it only as a utility method for the class itself.
    def __private_function(self):
        return 'Some text'
        

**Notice** the class attributes that are defined outside the constructor are static: they are shared by all objects of the class, and can be accessed throw the class name. For example:

In [94]:
PersonClass.nationality ## static variable call

'American'

In [95]:
PersonClass.capitalized_nationality()

'AMERICAN'

In [96]:
personInstance = PersonClass('Micheal', 'Jordan')
anotherPerson = PersonClass('Larry', 'Bird')

print(personInstance.firstName) ## this is an instance variable
print(anotherPerson.get_full_name()) ## this is an instance method

Person Constructor is Called
Person Constructor is Called
Micheal
Larry Bird


In [97]:
print(personInstance.__private_function()) ## this cannot be accessed

AttributeError: 'PersonClass' object has no attribute '__private_function'

In [98]:
print(anotherPerson.capitalized_nationality()) ## access class method from instance object

AMERICAN


### Inheritance and Polymorphic Behavior

A class can inherit from another class. In effect, that gives the *child* class all the functionality of the *parent* class.

Polymorphism means that the *Child* class can *override* some of these functionalities if needed.

In [100]:
class WomanClass(PersonClass):
    
    
    def __init__(self, firstName, lastName):
        
        ## since base class has no default constructor, we must call it
        PersonClass.__init__(self, firstName, lastName)
    
    ## special method to this class
    def my_gender(self):  
            print("I am a female")
        
    ## override the get_full_name from the base class
    def get_full_name(self):
        return f"Mizz. {self.firstName} {self.lastName}" 


    ## private method since women NEVER reveal their age o.O
    def __get_age():
        pass

In [101]:
womanInstance = WomanClass('Scarlett', 'Johansson')

print(womanInstance.get_full_name()) ## call overridden function
print(womanInstance.capitalized_nationality()) ## call function from base class
womanInstance.my_gender() ## call derived class function

Person Constructor is Called
Mizz. Scarlett Johansson
AMERICAN
I am a female


---------------------

## File IO

Dealing with files is very important in Python, yet very simple.

The `open` function is used to deal with files. It takes the *file path* as its first argument and the *mode* as its second. The file path can be relative or absolute. The mode is a string of flag characters that controls how the file will be used, for example, `'w'` for writing, `'r'` for reading, `'a'` for appending, etc., and it defaults to `'r'`.

In [102]:
file = open('myfile.txt', 'w')  # opening a file in the same working directory named myfile.txt
print(file)

<_io.TextIOWrapper name='myfile.txt' mode='w' encoding='cp1252'>


We can write anything in the file

In [103]:
file.write("Hello!\nI am writing this file using Python!")
file.close()

We then can read the file contents again using the readLines() function to read the file lines at once. 

In [104]:
fileReader = open('myfile.txt', 'r') # open file in reading mode

## loop over the file lines:

for line in fileReader.readlines():
    print(line)
    
    
## donot forget to close the file handler
fileReader.close()

Hello!

I am writing this file using Python!


**GOOD PRACTICE** to always use `open` in `with` statements to automatically release the file!

In [105]:
with open('myfile.txt', 'r') as fileReader:
    for line in fileReader:
        print(line.rstrip())
fileReader.close()

Hello!
I am writing this file using Python!


---------------------

# REAL Python Starts Here
Until now, all we discussed was the syntax of crude Python operations. It is important to know it and not fall in Syntax errors, but crude Python is slower than most porgramming languages. That is why libraries like NumPy, Pandas, and Matplot-Lib not only allow you to use ready made functionalities, they are **MUCH** faster than normal Python operations.

**NOTICE** in upcoming labs, you will be evaluated on performance, so make sure 
you understand these libraries very well.

# NUMPY
The first important library you **MUST** use whenever it comes to matrix/vector operations.

Numpy is a general purpose **Array** processing package. It provides high-performance multidimensional array objects, with operations over them, that make them very computationally efficient. 

Think of NumPy as a special kind of ARRAYS called `ndarrays`, where these arrays are very fast, dynamic in length, and have their associated operations like matrix multiplication, summation of elements, getting maximum element, and many other array operations that are efficient.

**HOW** does NumPy achieve efficient operations? 

For a starter, NumPy is written and compiled in C not python (that's why it is much faster than Python).

But more importantly, NumPy allows for **Parallelization** (and this HIGHLY depends on the code you write). 

## How to use numpy
First you need to have the package installed on your python package manager (ANACONDA) using the command `conda install numpy`.

Then you import the package modules to your work script using:

`import numpy as np`

**GOOD PRACTICE** the `as np` in the last command is not mandatory, it is called an alias (or nickname) for the package so you can use `np` instead of `numpy`. A common practice is to use `np` to refer to `numpy`, and we will use `pd` for pandas and `plt` for `matplotlib` as you will see later in the file 

In [107]:
## import numpy to the file
import numpy as np

## Arrays in NumPy
Arrays in NumPy are like Matrices. 1D arrays are called `vectors`, and nD arrays are high dimentional matrices, for example 2D. 


**VERY IMPORTANT** For 2D matrices, the shape is (`row ,column`), and vectors in the matrices in NumPy are **Horizontal** not vertical like we learn in linear algebra.

There are multiple easy ways to create array objects from numpy.

### 1. Create arrays from Lists values

In [116]:
## create array from values
np_arr = np.array([1, 2, 3, 4]) ##

## print it:
print(np_arr, "is of type", type(np_arr))

## use array_name.shape to get array shape
# if we have a 1D array, the shape will be (n,) where n is the number of elements, which is the # of columns only.
print("Its shape is", np_arr.shape , "this is the number of columns and rows", sep= "  ")  

## use array_name.dtyoe to get type of array elements
print("Its data type", np_arr.dtype)

[1 2 3 4] is of type <class 'numpy.ndarray'>
Its shape is  (4,)  this is the number of columns and rows
Its data type int32


**IMPORTANT** Unlike lists in Python, NumPy arrays should have the same data type fro **ALL** its elements

In [114]:
## create 2D array
two_dim_array = np.array([ [1, 2, 3,4], [4, 5, 6,5], [7,2, 8, 9]]) ## each of the [1, 2, 3] [4, 5, 6] and [7, 8, 9] is a VECTOR

## print it
print(two_dim_array)   ## observe how the vectors above are Horizontal not vertical

## print single item 
print(two_dim_array[1][2]) # I expect 6 -> correct :)

## get its shape
print("Its shape is", two_dim_array.shape)  

## get its data type
print("Its data type", two_dim_array.dtype)

[[1 2 3 4]
 [4 5 6 5]
 [7 2 8 9]]
6
Its shape is (3, 4)
Its data type int32


### 2. Create Common types of arrays

In [117]:
## create an empty array of size 3*2
arr = np.empty((3,2)) 
print(arr) ## non initialized array 

[[4.24399158e-314 8.48798317e-314]
 [1.06099790e-313 1.06099790e-313]
 [4.24399159e-314 1.90979621e-313]]


In [119]:
## create identity matrix of size 5*5 
#### (Remember, identity matrix has 1s on diagonals and 0s otherwise, and it is always a square matrix)
identity = np.eye(5) # eye is the identity matrix function

print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [120]:
## create array full of 1s  of size 3*4
all_ones = np.ones((3, 4))  
print(all_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [121]:
## create array full of zeros of size 2*2
all_zeros = np.zeros((2,2))
print(all_zeros)

[[0. 0.]
 [0. 0.]]


In [122]:
## create array full of specified value (here character 'a') of size 3*2
all_a = np.full((3,2), 'a')
print(all_a)

[['a' 'a']
 ['a' 'a']
 ['a' 'a']]


### Test yourself:
* [x] try to build the ones and zeros method using the full method

In [126]:
all_zeros = np.full((2,4), 0)
all_ones = np.full((4,2), 1)

print(all_zeros, all_ones, sep= "\n-----------------\n")

[[0 0 0 0]
 [0 0 0 0]]
-----------------
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


## Matrix Operations in NumPy

NumPy allows many built-in matrix operations that are very useful

In [127]:
## reshape matrix
mat = np.array([ [1, 2], [3, 4], [5, 6]]) 

print('old matrix ', mat)
print('old shape is ', mat.shape)

## then reshape it to 6*1 array
mat = mat.reshape(6,1)
print('new matrix', mat)
print(' new shape is', mat.shape)

old matrix  [[1 2]
 [3 4]
 [5 6]]
old shape is  (3, 2)
new matrix [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
 new shape is (6, 1)


**REMEMBER** The number of elements is the same in the new matrix and the old matrix, so make sure the new dimension are equivalent to that.

i.e.: the rows_old * columns_old = rows_new * columns_new

This is useful because:

If you know one dimension of the new matrix, but not sure the other dimension, you can let NumPy guess it by placing -1 instead of the new dimension value. **REMEMBER** you can use -1 for only one of the dimensions.

In [128]:
mat = np.ones((7,4)) ## a 7*4 matrix

## i want to reshape it to 1D array! i knwo it would look like (x,1) but don't knwo what x should be
new_matrix = mat.reshape(-1,1) # reshape to 1D array

print(new_matrix.shape) ## it correctly reshaped it!

(28, 1)


In [130]:
## Transposing a matrixc is mat.T:
mat = np.array([ [1, 2], [3, 4], [5, 6]]) 

print('transponse of ', mat, 'is',  mat.T, sep='\n ------------------\n')

transponse of 
 ------------------
[[1 2]
 [3 4]
 [5 6]]
 ------------------
is
 ------------------
[[1 3 5]
 [2 4 6]]


In [131]:
## Matrix by Matrix Multiplication using np.dot:
mat1 = np.array([ [1, 2], [3, 4], [5, 6]])  ## of shape 3*2
mat2 = np.array([[1, 3, 5], [2, 4, 6]]) ## of shape 2*3

## result matrix is of shape 3*3
mat1_by_mat2 = np.dot(mat1, mat2) ## rememeber, inner dimensions must be the similar -> 2*3 and 3*2 , but not 3*4 and 2*3 for example.
  
print(mat1_by_mat2)
print('result shape: ', mat1_by_mat2.shape)

[[ 5 11 17]
 [11 25 39]
 [17 39 61]]
result shape:  (3, 3)


In [132]:
## similar to np.dot, the @ can be used to multiply two matrices arithmatically
mat1 = np.array([ [1, 2], [3, 4], [5, 6]])  ## of shape 3*2
mat2 = np.array([[1, 3, 5], [2, 4, 6]]) ## of shape 2*3

mat1_by_mat2 = mat1@mat2 # very nice operator overloading :)

print(mat1_by_mat2) ## same result
print('result shape: ', mat1_by_mat2.shape)

[[ 5 11 17]
 [11 25 39]
 [17 39 61]]
result shape:  (3, 3)


In [134]:
## the astrisk * is used for element-wise multiplication -> bdrb kol element fl element el osado
mat1 = np.array([ [1, 2], [3, 4], [5, 6]])  ## of shape 3*2
mat2 = np.array([ [1, 5], [5, 5], [5, 6]])  ## of shape 3*2

mat1_elements_by_mat2_elements = mat1*mat2 ## they MUST be of the same size
print(mat1_elements_by_mat2_elements)
print('result shape: ', mat1_elements_by_mat2_elements.shape)

[[ 1 10]
 [15 20]
 [25 36]]
result shape:  (3, 2)


## Broadcasting in NumPy

Broadcasting is the MOST important concept in numpy. The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations.

In Mathematics, in order to multiply two matrices, their inner dimensions must be equal. for example, if matrix A is of shape `r1*c1`, and matrix B is of shape `r2*c2`, the multiplication is valid only if `c1 is equal to r2`.

However, in numpy, it allows for this operation to occurr if c1 is not equal to r2 under certain conditions.

For example:
if we want to add 5 to all values of the array [1, 2, 3] it goes like this: 

In [135]:
arr = np.array([1, 2, 3])
arr_plus_5 = arr + 5
print(arr_plus_5) 

[6 7 8]


What happened here is that the value 5 is broadcasted to all elements of the array `arr`. Broadcasting means it is **REPEATED** until the shapes are equivalent to perform the `addition` operation.

Another example is if we have the matrix  

`[ [1, 2, 3]
   [1, 2, 3]
   [1, 2, 3]]`
   
and we want to multiply the first column by 2, the second column by 3, and the third column by 4. 

We can do that using broadcasting of array [2, 3, 4] over the matrix. See:

In [137]:
## create our matrix
mat = np.array([ [1, 2, 3], [1, 2, 3], [1, 2, 3]])

## the multiplication values
multiplication_vals = np.array([2, 3, 4])

## then perform the multiplication using broadcasting:

print(mat*multiplication_vals) # very nice!!! :)

[[ 2  6 12]
 [ 2  6 12]
 [ 2  6 12]]


What happened here is that NumPy found the shape of the first matrix is (3,3) and the second one is (3,) so it repeated the **Smaller** matrix until its shape is like the first one (i.e made it 3 * 3 matrix) then multiplied each element by the corresponding one.

## Array Slicing
Indexing arrays in NumPy is easy and useful. We can index sub-arrays, elements and vectors (horizontally and vertically)

In [138]:
mat = np.arange(25).reshape(5,5) ## create a 5*5 array

print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [141]:
## get the first row
print(mat[0]) ## similar to mat[0, :]
## get the 2nd column in numpy
print(mat[:, 1]) # we must put : to get all rows, and then the column index

[0 1 2 3 4]
[ 1  6 11 16 21]


In [142]:
## get the sub array of elements from index (1,1) through the index (3,4)
print(mat[1:4, 1:5]) ## we want rows 1,2 and 3. and columns 1,2,3,4 -> still last index is always excluded.

[[ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]


## Masked Indexing

Another important concept in NumPy is the Masked indexing. We can treat elements of arrays as one object, and index over them using operations.

To check which elements of an array are positive:

In [143]:
arr = np.array([-1, 0, 5, 6, -2, 7, 9, -4]) ## defined array

print(arr>0) ## returns a list of truth (True for +ve and False for non-positive values)

[False False  True  True False  True  True False]


We can use this returned list to index from the array itself.

For example:

In [144]:
positive_numbers = arr[ arr>0 ]  ## the condition returns a list of truth (Mask) which is used to index the array itself
print(positive_numbers) # arr>0 is a maskk, and arr[mask] is the indexing, this means that it iterate over the indcies, and if it was true it returns this index.

[5 6 7 9]


We can use the mask to alter the values of the array itself. 

For example, we want to replace all even values in a list with -1:

In [145]:
array = np.array([1, 2, 3, 4, 5, 6, 7]) ## 

array[ array%2==0 ] = -1 ## the mask returns true for even values, and false for odd values. 
                         ## Then it indexes from the array itsef and assigns -1 to the indices of True values in the mask
print(array)

[ 1 -1  3 -1  5 -1  7]


## Aggregation

NumPy provides a lot of common aggregation functions for arrays.

> Aggregation means built in functions related to the arrays

In [146]:
 # sum, mean, var, std and A LOT more!
arr = np.arange(5) ## similar to np.array([0, 1, 2, 3, 4])
print(arr.mean())    

# If axis is specified, the function does not over the whole array

arr = np.arange(10).reshape(5,2) ## creates a 5*2 array of values from 0-9
print(arr.mean(axis=0))  ## axis = 0 means it creates the mean over the columns (0-> colums, 1->rows)

print(arr.mean(axis=1)) ## axis = 1 for means of rows

2.0
[4. 5.]
[0.5 2.5 4.5 6.5 8.5]


---------------------

# Pandas
Pandas is a library for reading, writing and manipulating datasets, usually in tabular format.

Using Pandas is very similar to NumPy:

In [147]:
## import Pandas package to your workspace
import pandas as pd

Pandas is a library for reading, writing and manipulating datasets, usually in tabular format. It has two main data structures; `Series` which is similar to a NumPy arrays and `DataFrame` which is similar to 2D NumPy arrays. A `DataFrame` is essentially comprised of one or more `Series`. Its usage is very similar to NumPy's! Since its usage is very similar to NumPy's (which underlies a lot of its functionalities), let's jump ahead to using it with datasets!

We will be using UCI's famous [Iris dataset](https://www.kaggle.com/uciml/iris).

## Reading Data Files in Pandas
Pandas have multiple data file readers like CSV, TSV, JSON and many others. 

When the data is read, it is parsed into a DataFrame data type. Think of DataFrames as Named Tables where the columns of the tables have names and indexes, and rows are the rows are the entries for each column.

To read a CSV file, we use Panda's ready-made function read_csv.

Notice how the data is stored in a table-like data structure. That makes them easy to work on and use.

In [149]:
## read the Iris dataset into a dataframe
iris_data = pd.read_csv('Iris.csv', sep=',') # the sep argument is the separator of the file. Here: a comma separated file (csv)

## print the first 5 rows of the table to see how the dataframe is ordered:
iris_data.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [150]:
# To get the column names:
iris_data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

We can also get a brief summary for all data columns using the "describe()" function
* Count: the number of non-empty entries for the column
* mean: the arithmetic mean of the column's data (if it were numeric)
* std: the standard deviation of the column's data (if it were numeric)
* min: minimum value in the column's entries (if it were numeric)
* 25%: the 25th percentile
* 50%: 50th percentile 
* 75%: 75th percentile
* max: maximum value in the column's entries (if it were numeric)

In [151]:
iris_data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [164]:
## get a random sample of 10 entries from the data:
iris_data.sample(10) 



Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
98    99            5.1           2.5            3.0           1.1   
53    54            5.5           2.3            4.0           1.3   
55    56            5.7           2.8            4.5           1.3   
60    61            5.0           2.0            3.5           1.0   
77    78            6.7           3.0            5.0           1.7   
138  139            6.0           3.0            4.8           1.8   
149  150            5.9           3.0            5.1           1.8   
40    41            5.0           3.5            1.3           0.3   
141  142            6.9           3.1            5.1           2.3   
20    21            5.4           3.4            1.7           0.2   

             Species  
98   Iris-versicolor  
53   Iris-versicolor  
55   Iris-versicolor  
60   Iris-versicolor  
77   Iris-versicolor  
138   Iris-virginica  
149   Iris-virginica  
40       Iris-setosa  
141   Iris-virginica  
20       Iris-setosa

**NOTICE** `head` returns n-elements from the begining, but `sample` returns n-elements randomly from the entire dataset

In [163]:
## get the first 10 entries from the data:
iris_data.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

## Indexing in Pandas
1. We can index throw the dataframe as if it were an 2D array using the `iloc`.

For example, to get all entries of the 3rd row starting from the 2nd column:

In [161]:
iris_data.iloc[2, 1:]

SepalLengthCm            4.7
SepalWidthCm             3.2
PetalLengthCm            1.3
PetalWidthCm             0.2
Species          Iris-setosa
Name: 2, dtype: object

2. We can index a dataframe column by name

In [165]:
iris_data.SepalLengthCm ## returns all the entries of the column 'SepalLengthCm'

## Equivalent to iris_data['SepalLengthCm']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

3. We can use Masked Indexing as well

For example, to get all entries of the column 'SepalLengthCm' that are under 5 centimeters:

In [166]:
iris_data[iris_data.SepalLengthCm < 5] 

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
6      7            4.6           3.4            1.4           0.3   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            4.3           3.0            1.1           0.1   
22    23            4.6           3.6            1.0           0.2   
24    25            4.8           3.4            1.9           0.2   
29    30            4.7           3.2            1.6           0.2   
30    31            4.8           3.1            1.6           0.2   
34    35            4.9           3.1            1.5           0.1   
37    38            4.9           3.1            1.5           0.1   
38    39            4.4           3.0            1.3           0.2   
41    42            4.5           2.3            1.3           0.3   
42    43            4.4           3.2            1.3           0.2   
45    46            4.8           3.0            1.4           0.3   
47    48            4.6           3.2            1.4           0.2   
57    58            4.9           2.4            3.3           1.0   
106  107            4.9           2.5            4.5           1.7   

             Species  
1        Iris-setosa  
2        Iris-setosa  
3        Iris-setosa  
6        Iris-setosa  
8        Iris-setosa  
9        Iris-setosa  
11       Iris-setosa  
12       Iris-setosa  
13       Iris-setosa  
22       Iris-setosa  
24       Iris-setosa  
29       Iris-setosa  
30       Iris-setosa  
34       Iris-setosa  
37       Iris-setosa  
38       Iris-setosa  
41       Iris-setosa  
42       Iris-setosa  
45       Iris-setosa  
47       Iris-setosa  
57   Iris-versicolor  
106   Iris-virginica

## Requirement on NumPy and Pandas

Test your knowledge in this requirement

In [ ]:
# Do the necessary imports here as you proceed in the requirement. 
import numpy as np
import pandas as pd
import time
np.random.seed(0) # Do not change this line

In [167]:
# [1] Define a numpy array A of zeros of size 3 in one line.
A = np.zeros(3)
print(A)

[0. 0. 0.]


In [168]:
## Test your code (No errors should be displayed)
assert np.any(A!=0) == False, "All elements of array A should be 0"
assert A.shape[0] == 3, "Array A should be of shape (3,1) or (3,)"

In [169]:
# [2] Define a numpy array B of ones of size 5 x 3 in one line.
B = np.ones((5,3))
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [170]:
## Test your code 
assert np.any(B!=1)==False, "All elements of array B should be 1"
assert B.shape == (5,3), "Array B should be of shape (5,3)"

|  |  |  |  |  |
|---|---|---|---|----|
| 2 | 4 | 0 | 1 | -3 |
| 5 | **3** | **2** | **8** | 7 |
| 4 | **6** | **9** | **3** | 2 |


In [182]:
# [3] Define a numpy array C containing the values above in one line
C = np.array([[2,4,0,1,-3], [5,3,2,8,7], [4,6,9,3,2]])
print(C)

[[ 2  4  0  1 -3]
 [ 5  3  2  8  7]
 [ 4  6  9  3  2]]


In [172]:
## Test your code 
assert C.shape == (3,5), "Array C should be of shape (3,5)"

In [173]:
# [4] Transpose the array C and store the transpose in array D. 
## (Do this using two different methods for transposing the array)
D = C.T
print(D)

[[ 2  5  4]
 [ 4  3  6]
 [ 0  2  9]
 [ 1  8  3]
 [-3  7  2]]


In [174]:
## Test your code 
assert D.shape == (5,3), "Array D should be of shape (5,3)"

In [175]:
# [5] Add to every element in C a constant value of 5 and store the array in E in one line. 
## (What will happen if C was a list and not a numpy array? Provide a textual answer for that question after you try it in a side cell)
E = C + 5
print(E)

[[ 7  9  5  6  2]
 [10  8  7 13 12]
 [ 9 11 14  8  7]]


##### What will Happen is that: 
* an error wiil be raised, because it will expect to recieve a list not an integer. 
* this is due to the fact that normal lists in python don't have the ability of broadcasting; which is the major ability and feature in the numpy library

In [181]:
# C = [[2,4,0,1,-3], [5,3,2,8,7], [4,6,9,3,2]]
# E = C + 5
# print(E)

In [178]:
## Test your code 
assert E.shape == (3,5), "Array E should be of shape (3,5)"
diff = E - C
assert np.all(diff==5), "E is not correctly calculated"

In [187]:
# [6] Extract the bold elements in C and store the submatrix in array F in one line. 
F = C[1: , 1:-1] # from 1 to end of rows, and from 1 to end-1 of columns, using negavite indexing for practicality.
print(F)

[[3 2 8]
 [6 9 3]]


In [186]:
## Test your code 
assert F.shape == (2,3), "Array F should be of shape (2,3)"
assert F[0,0] == F[1,2] == 3, "Wrong slicing"

In [188]:
# [7]  Reshape the matrix C into another array G of shape (1, 15) in one line.
## Hint: what does np.reshape(1,-1) do? What does the negative mean here? (Provide a textual answer for that question)
G = C.reshape(1,15)
print(G)

[[ 2  4  0  1 -3  5  3  2  8  7  4  6  9  3  2]]


> This will compute the 15 alone, and this is a feature implemented in case that you forgot or don't know how to compute the second diminsion, but note that you must specify at least one of the two diminsions

In [190]:
## Test your code 
assert G.shape == (1,15), "Array G should be of shape (1,15)"

In [191]:
# [8] Which elements of G are even numbers? 
# Return a boolean array H such that elements corresponding to even numbers are considered TRUE and those 
# corresponding to odd numbers are considered FALSE. 
H = G %2 == 0
print(H)

[[ True  True  True False False False False  True  True False  True  True
  False False  True]]


In [192]:
## Test your code 
assert np.sum(H) == 8, "Array H returned True for Odd elements"

In [193]:
# [9]  Return a vector J containing the actual elements that are even in one line
J = G[G %2 == 0]
print(J)

[2 4 0 2 8 4 6 2]


In [194]:
## Test your code 
assert np.sum(J)==28, "Array J returned Odd elements"

In [195]:
np.random.seed(0) #Do not change this line
# [10] Define a random array L 5 x 3 in one line. (use np.random.rand(shape))
L = np.random.rand(5,3)
print(L)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]]


In [196]:
## Test your code 
assert L.shape == (5,3), "Array L should be of shape (5,3)"

In [ ]:
# [11] What is the difference between np.random.rand() and np.random.randn()?

## ANSWER: 

### HINT: read (https://numpy.org/devdocs/reference/random/generated/numpy.random.randn.html)
###       read (https://numpy.org/devdocs/reference/random/generated/numpy.random.rand.html)

In [198]:
# [12] Perform element-wise multiplication between D and L by two different methods, each in one line.
element_wise = D*L

In [199]:
## Test your code 
assert element_wise.shape == (5,3), "Element wise multiplication should give array of the same size"

In [205]:
# [13] Do a matrix multiplication between D and the transpose of L using two different methods, each in one line.
mat_multiplication_1 = D@L.T
mat_multiplication_2 = np.dot(D,L.T)

In [206]:
## Test your code 
assert mat_multiplication_1.shape == (5,5), "Matrix multiplication of (5*3) and (3,5) should give array of shape (5,5)"
assert mat_multiplication_2.shape == (5,5), "Matrix multiplication of (5*3) and (3,5) should give array of shape (5,5)"

In [212]:
# [14] We want to implement a function that computes y = sqrt(9-x^2). Write a function that accepts all these calls. 
# y1 = your_function(3)
# y2 = your_function(np.array([3,2]))
# y3 = your_function(np.array([3,2,1]))
def func(list):
  if(type(list) == int):
    return np.sqrt(9-list**2)
  elif (type(list) == np.ndarray):
    for i in list:
      return np.sqrt(9-i**2)

0.0


In [211]:
assert func(3) == 0
assert np.all(func(np.array([3,3])) == 0)
assert np.all(func(np.array([3,3,3])) == 0)

In [221]:
import time
np.random.seed(0) #Do not change this line
# [15] Generate a random array M of size 100,000 . Use np.random.randint. 
M = np.random.randint(low = -50000, high=100000 ,size= 100000)

# [15a] Retrieve the elements greater than zero using for loop. Place your code between timers as shown.
start = time.time()
# TODO: Your code here
positives = []
for value in M:
    if value > 0:
        positives.append(value)
end = time.time()
print(end - start)

# [15b] Retrieve the elements greater than zero using list comprehension. Place your code between timers as shown.
start = time.time()
positives1 = [value for  value in M if value > 0]
end = time.time()
print(end - start)

# [15c] Retrieve the elements greater than zero using vectorization (masking). Place your code between timers as shown. 
start = time.time()
positives2 = M[M > 0]
end = time.time()
print(end - start)



0.018986940383911133
True
0.016005277633666992
[ True  True  True ...  True  True  True]
0.004996776580810547


In [ ]:
# [16] Compare between the difference between time elapsed using loop, list comprehension and vectorization respectively.
# Provide a textual answer. Can you compute the gain in performance in each? (Do not write code for that. You can just calculate it)
## ANSWER:
# The time elapsed using loop is 0.018986940383911133
# The time elapsed using list comprehension is 0.016005277633666992
# The time elapsed using vectorization is 0.004996776580810547
# so it is obvious that vectorization is the fastest method.
# The gain in performance is (new - old) / old * 100


In [223]:
N = np.array([2,1,7,9,4,6])
# [17] Find the maximum element in N its index 
max = N.max()
maxIndex = N.argmax()
print(max)
print(maxIndex)

9
3


In [224]:
# [18] Find the mean and standard deviation of values in M
mean = N.mean()
std_dev = N.std()
print(mean)
print(std_dev)

4.833333333333333
2.793842435706702


In [230]:
# [19a] Read the text file "test.txt" into an a numpy array N
N = np.loadtxt("test.txt")
print(N)

# [19b] Convert N into numpy array. (Hint: use np.asarray())
N = np.asarray(N)
print(N)

ValueError: could not convert string to float: '1,2,1'

In [ ]:
## Test your code 
assert N.shape == (10,3), "Incorrect dimensions of N"

In [ ]:
# [20] Print only the rows containing (1) in the last column for each row of matrix N IN ONE LINE. This should print rows 0, 1, 3, 6, 8, and 9.
# This should print actual rows not the number of rows. Assign the output of this selection to variable O
O = None
print(O)

In [ ]:
## Test your code 
assert O.shape == (6,3), "Incorrect dimensions of O"
assert np.all(O[:,2] == 1), "Wrong slicing or masking"

In [ ]:
# [21] Print only the first two elements of rows containing (1) in the last column for each row of matrix N in ONE LINE. 
# This should print the first two columns of the same lines as the previous requirement.
# Assign the output of this selection to variable P
P = None
print(P)

In [ ]:
## Test your code 
assert P.shape == (6,2), "Incorrect dimensions of P"
assert np.sum(P) == 20, "Wrong slicing or masking"

In [ ]:
# [22] Display the mean value for each column in N in ONE LINE. Hint: Check the axis dimension. 
mean = None
print(mean)

# MatplotLib

Matplotlib is one of the most famous and used libraries for visualizations in Python. It has a very expressive API for most used types of graphs.

In [ ]:
# import MatplotLib to your work file
from matplotlib import pyplot as plt
import pandas as pd

iris_data = pd.read_csv('Iris.csv') ## we will use these data for plotting

## Line Plots
Line plots are typically used to visualize continuous data sequences like time series, e.g., readings from a sensor, stock market daily data, etc.

1. Plotting one variable 

By default, pyplot will plot that variable against a sequence of its length starting at 0

In [ ]:
plt.plot(iris_data.SepalLengthCm.values) 
plt.show()

2. Plotting two variables against each other

In [ ]:
plt.plot(iris_data.SepalLengthCm.values, iris_data.SepalWidthCm.values)  
plt.show()

In [ ]:
# Plotting Known functions: f(x) = x^2 will give a parabola centered at Zero
x = np.linspace(-100, 100)
plt.plot(x, x**2)
plt.show()

## Scatter Plots
Scatter is almost always the first plot to try with unordered data samples.
It places shapes at the data points' location

In [ ]:
plt.scatter(iris_data.SepalLengthCm.values, iris_data.SepalWidthCm.values)
plt.show()

**OBSERVE** how using the Scatter plot gives a more meaningful graph than the line plot. Here: scatter plot shows how the Sepal Length is distributed against the Width (dense at certain values and scarce at others). This distribution was not shown in the line plot.

Plotting your data can help you understand things about them. Using the **correct** plot is important.  

## Histogram Plots
Histogram counts the values frequencies. For example, an array of values `[1, 1, 2, 3, 3, 5, 5, 5, 5]` will have a histogram like this: 
`[
1: 2, # because 1 is repeated twice
2: 1, # because 2 exists only once
3: 2,
5: 4
]`

PyPlot has a built in `hist` function to plot histogram of values easily.

In [ ]:
plt.hist(iris_data.Species)
plt.show()

## Pie Charts
Pie charts can serve the same role as histograms, and sometimes better at understanding

In [ ]:
pie_data = iris_data.Species.value_counts() ## get the histogram but from pandas: the values_counts counts the frequency of each value
plt.pie(pie_data.values, labels=pie_data.index) ## labels are given the spicies' names
plt.show()

**NOTICE** the graph will not be printed until the function plt.show() is called.

## Multiple Plots on the Same Figure

It is useful for plotting multiple data on the same figure. 

For example: to plot both the SepalLengthCm (in red) and the PetalLengthCm (in blue) versus the SepalWidthCm

In [ ]:
plt.scatter(iris_data.SepalLengthCm.values, iris_data.SepalWidthCm.values, c='red', marker='s', alpha=0.8, edgecolors='none', s=25) ## s in marker means put a square at data points
plt.scatter(iris_data.PetalLengthCm.values, iris_data.SepalWidthCm.values, c='blue', marker='^',  alpha=0.8, edgecolors='none', s=25) ## ^ means triangles
plt.show()

## Requirement on MatPlotLib

For plotting, import matplotlib.pyplot as plt

x = np.linspace(0,3,300)

y = your_function(x)

Plot x versus y in one line with red color.  What does np.linspace mean?


In [ ]:
## Answer:
