In [1]:
#You declare the variable without type.
a = 3
b = True
c = 'String!'
print(a,b,c)

3 True String!


In [1]:
print(5/2)
print(int(5/2))

2.5
2


In [3]:
#Loops
arr = [1,2,3,4,5]
print('show array with for in')
for x in arr:
    print(x)
print('show array with for in range')
for x in range(len(arr)):
    print(arr[x])
print('show even numbers')
for x in arr:
    if x%2 == 0:
        print(x)


show array with for in
1
2
3
4
5
show array with for in range
1
2
3
4
5
show even numbers
2
4


In [9]:
# Array Indexing:
arr = [0,1,2,3,4,5]
print(arr[0:3]) # the 3 is excluded.

import numpy as np


# this is one Diminsion array but using the numpy library which is much faster and efficient than 
# python arrays 
origMat = np.array(arr)
mat = np.copy(origMat)
print(mat)
mat[0:3] = 0 # 0 1 2 only will get that value
print(mat)
mat = np.copy(origMat)
mat[(mat%2==0)] = -1 # here we place -1 in the even indicies only
print(mat)

[0, 1, 2]
[0 1 2 3 4 5]
[0 0 0 3 4 5]
[-1  1 -1  3 -1  5]


In [5]:
origMat = np.array([ # implementing 2D matrix 
                   [1,2,3,4,5],
                   [1,2,3,4,5],
                   [1,2,3,4,5]
                   ])
mat = np.copy(origMat)
print(mat)
mat[1:3,1:3] = 0 # (1,1), (1,2), (2,1), (2,2)
print(mat)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 0 0 4 5]
 [1 0 0 4 5]]


In [6]:
arrZeros = np.zeros((6,5)) # this is how we define the mat which contains zeros, 6 rows and 5 columns
arrOnes =np.ones((6,5)) # this is how we define the mat which contains ones 
print(arrZeros)
print(arrOnes)
print(arrOnes.shape) # shape returns a tuple of the diminsions of the mat or the mat (#rows, #columns, #3rdDimm, ... and so on)
print(arrOnes.shape[0]) # returns the number of rows only

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(6, 5)
6


In [11]:
# Shows the fact that Python uses KEYWORD ARGUMENTS as well as the traditional positional arguments.
## Notice that: in the output of the first and second call to function fun are the same.
## In the second call (using keywords arguments), sorting arguments is not needed.


def fun(x,y,z):
    print (x,y,z)
    
fun(1,2,3)
fun(z=3,y=2,x=1) # this is a better version because we can indicate which value to which element

1 2 3
1 2 3


In [12]:
#instead of NULL: None

x = None
if (x==None):
    print('x is None')


x is None
